name = "newsnow-project"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "bbd4a77b-d58d-4288-aebb-20e4942aaa0a"      # 替换为你创建的数据库 ID
